app/stories/__init__.py
"""
stories blueprint
Contains the routes for creating a story, viewing an individual stories, viewing the stories catalog
"""
from flask import Blueprint

stories = Blueprint('stories', __name__)

from app.stories import views

app/stories/views.py
"""
View functions for story functionality
"""
from app.stories import stories
from flask import render_template, abort
from sqlalchemy.orm.exc import NoResultFound

from app.constants.video_url import (
    YOUTUBE_FULL_URL,
    YOUTUBE_FULL_URL_SPLIT,
    YOUTUBE_EMBED_URL,
    YOUTUBE_SHORT_URL,
    VIMEO_STRING,
    VIMEO_URL,
    VIMEO_EMBED_URL
)
from app.models import Stories, Tags, Users


@stories.route('/catalog/', methods=['GET'])
@stories.route('/stories/', methods=['GET'])
def catalog():
    return render_template(
        'stories/stories.html',
        tags=Tags.query.all()
    )


@stories.route('/catalog/<story_id>', methods=['GET'])
@stories.route('/stories/<story_id>', methods=['GET'])
def view(story_id):
    try:
        story = Stories.query.filter_by(id=story_id).one()
        assert story.is_visible
    except NoResultFound:
        print("Story does not exist")
        return abort(404)
    except AssertionError:
        print("Story is not visible")
        return abort(404)

    if story.is_visible:
        user = Users.query.filter_by(guid=story.user_guid).one() if story.user_guid else None

        video_url = None
        if story.video_url:
            video_url = story.video_url
            if YOUTUBE_FULL_URL in video_url:
                split = video_url.split(YOUTUBE_FULL_URL_SPLIT, 1)
                video_url = YOUTUBE_EMBED_URL.format(split[1])
            elif YOUTUBE_SHORT_URL in video_url:
                split = video_url.split(YOUTUBE_SHORT_URL, 1)
                video_url = YOUTUBE_EMBED_URL.format(split[1])
            elif VIMEO_STRING in video_url:
                split = video_url.split(VIMEO_URL, 1)
                video_url = VIMEO_EMBED_URL.format(split[1])
        return render_template('stories/view.html', story=story, user=user, video_url=video_url)

app/templates/stories/result.html
{% for story in stories %}
    <a href="{{ url_for('stories.view', story_id=story['_id']) }}">
        <div class="home-story col-lg-3 col-md-4">
            <div class="home-story-content">
                <h4>{{ story['_source']['activist_first'] }}&nbsp;{{ story['_source']['activist_last'] }}</h4>
                {% if story['_source']['image_url'] %}
                    {% if story['_source']['content']|length < 50 %}
                        <p>{{ story['_source']['content'] }}</p>
                    {% else %}
                        <p>{{ story['_source']['content']|truncate(50) }}</p>
                    {% endif %}
                    <div class="img-mask" style="background-image: url({{ story['_source']['image_url'] }});">
                {% else %}
                    {% if story['_source']['content']|length < 350 %}
                        <p>{{ story['_source']['content'] }}</p>
                    {% else %}
                        <p>{{ story['_source']['content']|truncate(350) }}</p>
                    {% endif %}
                {% endif %}
                </div>
            </div>
        </div>
    </a>
{% endfor %}

app/templates/stories/stories.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid" id="search-head">
        <h1>I'm Looking for Women Known For</h1>
        <p>You may choose more than one category to narrow your search.</p>
        <input type="text" id="search" placeholder="Find by name or content"/><br/>
        <input type="hidden" name="start">
        <button id="search-btn">Search</button>
        <div id="search-tags">
            <div>
                <input type="text" placeholder="" id="hidden-search-tag-input" data-parsley-required
                       style="color: black;"/>
            </div>
            <div class="search-tags-group" data-toggle="buttons">
                {% for tag in tags %}
                    <button type="button" class="search-tag search-tag-inactive" value="{{ tag.id }}">{{ tag.name }}</button>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="home-wrapper">
        <div class="container" id="home-stories"></div>
        <div id="back-to-top-div">
            <span class="glyphicon glyphicon-menu-up" id="back-to-top-icon" aria-hidden="true"></span>
            <span id="back-to-top">Back to Top</span>
        </div>
    </div>
{% endblock %}

{% block custom_script %}
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/plugins/parsley.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/stories/search.js') }}"></script>
{% endblock %}

app/templates/stories/view.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid" id="view-story-container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{ story.activist_first }} {{ story.activist_last }}</h1>

                {% if story.activist_start and story.activist_end %}
                    <p id="story-subheading">{{ story.activist_start }} - {% if story.activist_end %}
                        {{ story.activist_end if story.activist_end != 9999 else 'Today' }}{% endif %}</p>
                {% endif %}

                <p id="story-user-date-subheading">{% if user %}
                    <strong>By: </strong> {% if user.first_name and user.last_name %}
                        {{ user.first_name }} {{ user.last_name }}
                        {% elif user.first_name %}{{ user.first_name }}
                        {% elif user.last_name %}{{ user.last_name }}
                    {% endif %}| {% endif %}
                    <strong>Date Added: </strong>{{ moment(story.date_created).format('MMMM D, YYYY') }}</p>

                <div id="story-content-container">
                    {% if story.image_url and video_url %}
                        <div id="view-story-center-wrap">
                            <img src="{{ story.image_url }}" id="view-story-img-short"/>
                            <div id="video-wrapper">
                                <iframe class="youtube-player" type="text/html" src="{{ video_url }}" frameborder="0"
                                            allowFullScreen></iframe>
                            </div>
                            <p>{{ story.content }}</p>
                        </div>
                    {% elif story.image_url and story.content|length > 1500 %}
                        <img src="{{ story.image_url }}" id="view-story-img"/>
                        <p>{{ story.content }}</p>
                    {% elif story.image_url and story.content|length < 1500 %}
                        <div id="view-story-center-wrap">
                            <img src="{{ story.image_url }}" id="view-story-img-short"/>
                            <p id="view-story-text-short">{{ story.content }}</p>
                        </div>
                    {% elif video_url %}
                        <div id="view-story-center-wrap">
                            <div id="video-wrapper">
                                <iframe class="youtube-player" type="text/html" src="{{ video_url }}" frameborder="0"
                                        allowFullScreen></iframe>
                            </div>
                            <p>{{ story.content }}</p>
                        </div>
                    {% else %}
                        <div id="view-story-center-wrap">
                            <p>{{ story.content }}</p>
                        </div>
                    {% endif %}

                    {% if story.activist_url %}
                        <p id="learn-more">To learn more, {% if story['activist_url'][:7] != 'http://' %}
                            <a href="http://{{ story.activist_url }}" target="_blank" id="learn-more-link">click
                                here</a>.
                        {% else %}
                            <a href="{{ story.activist_url }}" target="_blank">click here</a></p>
                        {% endif %}
                    {% endif %}

                </div>

            </div>
        </div>
    </div>

    <div id="view-story-social-div">
        <p>Share This Story</p>
        <div id="view-story-social">
            <a href="https://twitter.com/share?url={{ url_for('stories.view', story_id=story.id, _external=True) }}&text=I just posted a story about a woman activist who inspires me, you should too!&hashtags=20000By2020"
               target="_blank">
                <img src="{{ url_for('static', filename='img/twitter_icon.png') }}"/>
            </a>
            <a href="http://www.facebook.com/sharer.php?u={{ url_for('stories.view', story_id=story.id, _external=True) }}"
               target="_blank">
                <img src="{{ url_for('static', filename='img/facebook_icon.png') }}"/>
            </a>
        </div>
    </div>

    <div class="jumbotron" id="view-story-feedback-jumbotron">
        <div id="view-story-feedback-content">
            <h1>We'd Love Your Feedback</h1>
            <p>Share your thoughts on this story with us. Your comments will not be made public.</p>
            <a class="btn btn-default btn-lg" id="view-story-feedback-btn"
               href="mailto:womensactivism@records.nyc.gov" role="button">Email</a>
        </div>
    </div>
{% endblock %}